services:
  animal-scanner-frontend:
    image: animal-scanner-frontend:latest
    container_name: animal-scanner-frontend
    hostname: scanner-frontend
    build:
        context: ..
        dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - ../node_modules:/app/node_modules
    networks:
      - animal-explorer

networks:
    animal-explorer:
        driver: bridge
        name: animal-explorer-module
